In [1]:
import numpy as np
from vector_plot import plotVectors

In [2]:
x = np.array([1, 2, 3, 4, 5])

In [3]:
y = np.array([10, 20, 30, 40, 50])

In [4]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [5]:
m2 = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

In [6]:
# dot product of vectors - multiply elementwise and add
# it is commutative
# i.e. xTy = yTx where T is transpose
xdoty = np.dot(x, y)

In [7]:
# matrix product - i.e. dot product of rows(A) vs columns(B) of matrices
# can only work if dimensions match of rows of A and columns of B
mdotm2 = m @ m2

In [8]:
# hadamard product (elementwise multiplication of 2 matrices)
hdmrd = m * m2

In [9]:
# matmul is distributive
# A(B + C) = AB + AC
# matmul is associative
# A(BC) = (AB)C
# matmul is not commutative
# i.e. AB not always == BA

In [10]:
# transpose of matrix product
# (AB)T = BTAT
mm2_t1 = (m @ m2).T
mm2_t2 = (m2.T) @ (m.T)

In [11]:
print(mm2_t1)
print(mm2_t2)

[[ 30  84 138]
 [ 24  69 114]
 [ 18  54  90]]
[[ 30  84 138]
 [ 24  69 114]
 [ 18  54  90]]
